# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: code_execution.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'code_execution.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x63ode_execution.proto\">\n\x0b\x43odeRequest\x12\x10\n\x08language\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\x0f\n\x07\x61pi_key\x18\x03 \x01(\t\"#\n\x11\x45xecutionResponse\x12\x0e\n\x06output\x18\x01 \x01(\t\"2\n\x10\x43odeBatchRequest\x12\x1e\n\x08requests\x18\x01 \x03(\x0b\x32\x0c.CodeRequest\":\n\x11\x43odeBatchResponse\x12%\n\tresponses\x18\x01 \x03(\x0b\x32\x12.ExecutionResponse2Q\n\x14\x43odeExecutionService\x12\x39\n\x10\x45xecuteCodeBatch\x12\x11.CodeBatchRequest\x1a\x12.CodeBatchResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'code_execution_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CODEREQUEST']._serialized_start=24
  _globals['_CODEREQUEST']._serialized_end=86
  _globals['_EXECUTIONRESPONSE']._serialized_start=88
  _globals['_EXECUTIONRESPONSE']._serialized_end=123
  _globals['_CODEBATCHREQUEST']._serialized_start=125
  _globals['_CODEBATCHREQUEST']._serialized_end=175
  _globals['_CODEBATCHRESPONSE']._serialized_start=177
  _globals['_CODEBATCHRESPONSE']._serialized_end=235
  _globals['_CODEEXECUTIONSERVICE']._serialized_start=237
  _globals['_CODEEXECUTIONSERVICE']._serialized_end=318
# @@protoc_insertion_point(module_scope)
